version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123!
    ports:
      - "1434:1433"
    volumes:
      - sqldata:/var/opt/mssql
      - ./scripts:/scripts
    networks:
      - inventory-network
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Password123! -C -Q "SELECT 1"
      interval: 10s
      timeout: 5s
      retries: 5

  sql-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-init
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./scripts:/scripts
    networks:
      - inventory-network
    command: >
      /bin/bash -c "
      /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P Password123! -C -i /scripts/init-database.sql
      "
    restart: "no"

volumes:
  sqldata:

networks:
  inventory-network:
    driver: bridge